### PR TITLE
feat(Canvas): Add quick icon edge end

### PR DESCRIPTION
**Pull request by ibek**
| Horizontal | Vertical |
| --- | --- |
| image | image |

fix: https://github.com/KaotoIO/kaoto/issues/1540

### CODE REVIEW

**Comment by ibek** [comment]
[Uploading Screencast from 2024-10-13 18-24-51.webm…]()

**Comment by lordrip** [comment]
I like this a lot, I'm checking it in the vertical layout but it seems we should place the icon below the label.

Do you see another option?
image

**Comment by ibek** [comment]
Thank you @lordrip . For now I would keep it this way until we merge https://github.com/KaotoIO/kaoto/pull/1562 which suggests to place the labels on the right and then I can update the quick icon to be placed down which won't overlap like it would now.

**Comment by ibek** [comment]
As we discussed on Slack this is how it looks now in horizontal and vertical view:
Screenshot from 2024-10-14 22-36-55
Screenshot from 2024-10-14 20-39-39

**Comment by lordrip** [comment]
#### Horizontal
image

#### Vertical
image

**Pull request merged**
