### PR TITLE
Fix loading of Red Hat artifacts for catalog

### PR DESCRIPTION
**Pull request by apupier**
the test is passing locally for me despite i checked settings.xml to not have the red hat maven repoitory and remove the org.apache/camel folder from my .m2 so maybe another specific part is failing?

relates to https://github.com/KaotoIO/kaoto/issues/1597

### CODE REVIEW

**Comment by apupier** [comment]
I think the reason it works with the test and not from command-line is that camel-yaml-dsl artifact is part of the test dependencies, consequently the schema/camelYamlDsl.json is always picked from this one and not from what is loaded dynamically

**Comment by apupier** [comment]
io.kaoto.camelcatalog.maven.CamelCatalogVersionLoader.configureRepositories(String) is called too late for Camel Yaml DSL loading. it is called when loading Camel Catalogs.
Quick and dirty fix: switch order of loading catalog and camel yaml dsl in io.kaoto.camelcatalog.generator.CatalogGenerator.generate()
better: configuring repositories sooner, or ensuring each of the loader are loading the repositories if they need it

**Comment by apupier** [comment]
io.kaoto.camelcatalog.maven.CamelCatalogVersionLoader.configureRepositories(String)
is called too late for Camel Yaml DSL loading. it is called when loading
Camel Catalogs.
Quickfix provided: calling the CamelCatalog which is configuring the
repositories at first
not perfect as note all versions are aligned and some others might need
it but should be enough to unblock current situation

note that the provided is not efficient because the camel-yaml-dsl test
dependency is leaking in the other tests, thus even without the fix the
test is passing... I guess it would require to create a separate module
for the test or to ensure a specific version is picked (see also next
paragraph)

Another note: when several catalog are generated at same time, I'm not
sure that we can ensure that it picks the exact correct version of the
camel-yaml-dsl, it might be the first one found, whatever version it is;
To be checked. In practice I think that most of the time there are no
differences.

**Review by lhein — APPROVED** [review]

**Comment by lordrip** [comment]
When running
```
./mvnw package; java -jar ./target/catalog-generator-0.0.1-SNAPSHOT.jar -o ./dist/camel-catalog -k 4.6.0 -m 4.4.0.redhat-00045 -n "Default Catalog"
```
I got
image

**Review by lordrip — APPROVED** [review]

**Pull request merged**
